from PyQt5.QtGui import QColor

WINDOW_WIDTH = 400
WINDOW_HEIGHT = 300
WINDOW_CORNER_RADIUS = 20
BACKGROUND_COLOR = QColor(0, 100, 150, 140)
MASK_COLOR = QColor(0, 0, 0)
IMAGE_PATH = 'tank1.png'
ADJUST_HEIGHT = 45
ALLOW_FISH_EXIT = True
FISH_WIDTH = 30
FISH_HEIGHT = 16
FISH_PATH = 'fish.png'
FORCE_FACTOR = 2
FORCE_REDUCE_FACTOR = 2
MAX_TANK_DELTA = 15
FISH_EXIT_RANGE = 5